Added missing ctia code in clj-momo
threatgrid/clj-momo pull request #11
Opened 2017-04-28 13:07 UTC by yogsototh

Support #595

The added files will be really helpful to be create trapperkeeper service for riemann.

2017-04-28 13:20 UTC, msprunck commented
A riemann reporter already exists in the [metrics-clojure](https://github.com/sjl/metrics-clojure) library. Did you try it ? 

Furthermore, puppetlabs provides a trapperkeeper service for metrics [trapperkeeper-metrics](https://github.com/puppetlabs/trapperkeeper-metrics) with a graphite reporter. Riemann provides a graphite server to ingest events.

2017-04-28 13:21 UTC, gbuisson requested changes

2017-04-28 13:21 UTC, gbuisson commented on project.clj
> +                 [metosin/compojure-api "1.1.8"]
I think we shouldn't bundle compojure-api on clj-momo.

2017-04-28 14:23 UTC, polygloton commented on project.clj
> +                 [metosin/compojure-api "1.1.8"]
Its used in the metrics code.

2017-04-28 14:25 UTC, polygloton commented on project.clj
> +                 [metosin/compojure-api "1.1.8"]
Its only for one fn though.  Maybe we could pass in the fn.

2017-05-01 17:14 UTC, polygloton commented
Let's track this in #9

2017-05-01 17:14 UTC, closed without merging

2017-05-01 17:15 UTC, polygloton commented
I don't know the answer about the metrics-clojure library.  The issue that this work is for asks to extract the existing code out of CTIA into clj-momo.  If the code is not desired, that should be fixed in another issue.